---

- name: MYSQL | Install
  include: install.yml
  tags:
    - install

- name: MYSQL | Configure
  include: config.yml
  tags:
    - configure

- name: MYSQL | Users
  include: users.yml
  tags:
    - configure
    - users

- name: MYSQL | Databases
  include: databases.yml
  tags:
    - configure
    - databases

- name: MYSQL | Service
  include: service.yml
  tags:
    - service
