---
- name: MYSQL | Ensure MySQL users are present
  mysql_user:
    login_user: "{{ mysql_root_user }}"
    login_password: "{{ mysql_root_password }}"
    name: "{{ item.name }}"
    host: "{{ item.host | default('localhost') }}"
    password: "{{ item.password }}"
    priv: "{{  item.priv | default('*.*:USAGE') | join('/') }}"
    append_privs: yes
  with_items: "{{ mysql_users }}"
  #no_log: true
