---

galaxy_info:
  company: Idealista S.A.
  description: Prometheus jmx exporter
  min_ansible_version: 2.2
  license: Apache 2.0
  platforms:
    - name: Debian
      versions:
        - jessie
  categories:
    - database
